services:
  postgres:
    image: postgres
    container_name: postgres-conteiner
    ports:
      - "5433:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: filmflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8011
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pg-admin-conteiner
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network
    depends_on:
      - postgres
networks:
  app-network:




